spring:
  datasource:
      url: jdbc:mysql://rdsry5ng8fus2v021v53.mysql.rds.aliyuncs.com:3306/banma?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: banma
      password: banma123
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: alert

#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.alert.domain
  mapperLocations: classpath*:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

#oauth客户端配置
security:
  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**
  sessions: always
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: ssoclient
      client-secret: ssosecret
      access-token-uri: http://localhost:8091/oauth/token
      user-authorization-uri: http://localhost:8091/oauth/authorize
      client-authentication-scheme: form
    resource:
      jwt:
        key-uri: http://localhost:8091/oauth/token_key

#登出配置
sso:
  tosignout:
    url: http://localhost:8091/signout

oauthserver:
    getResource:
      function:
        url: http://localhost:8092/permission/function
      dataFunction:
        url: http://localhost:8092/permission/data
      userinfo:
        url: http://localhost:8092/user

#RestTemplate配置
client:
  filemanager:
     root:
        uri: http://filemanager.bmtrip.com
     connect:
        timeout: 5000
     read:
        timeout: 5000
  alert:
     root:
        uri: http://alert.bmtrip.com
     connect:
        timeout: 5000
     read:
        timeout: 5000
  report:
     root:
        uri: http://localhost:8101
     connect:
        timeout: 5000
     read:
        timeout: 5000
